### ISSUE TITLE
[Bump] Ember-appuniversum dependency conflict

### ISSUE THREAD

**Issue by FlorSanders** [redpencilio/ember-metis#8]
The [ember-appuniversum](https://github.com/appuniversum/ember-appuniversum) dependency [is set to version ^0.1.3](https://github.com/redpencilio/ember-metis/blob/master/package.json#L41), which causes dependency confilcts in e.g. [frontend-themis](https://github.com/kanselarij-vlaanderen/frontend-themis).
In npm 7 the install will fail if these are not resolved, unless the `--legacy-peer-deps` flag is used.

**Comment by Windvis** [comment]
This seems to have been resolved since this issue was created. Closing. Thanks!
